export const leadsData = [
  {
    name: "Acme Corp",
    source: "Referral",
    salesAgent: "69af8801fc00d3ee60bcd059",
    status: "New",
    tags: ["High Value", "Initial Inquiry"],
    timeToClose: 30,
    priority: "High",
  },
  {
    name: "BrightPath Solutions",
    source: "Website",
    salesAgent: "69af8b181716f5cd17e8e781",
    status: "Contacted",
    tags: ["Warm Lead", "Requested Demo"],
    timeToClose: 22,
    priority: "Medium",
  },
  {
    name: "NovaTech Ltd",
    source: "Cold Call",
    salesAgent: "69af8b361716f5cd17e8e784",
    status: "Qualified",
    tags: ["Enterprise", "Budget Confirmed"],
    timeToClose: 25,
    priority: "High",
  },
  {
    name: "GreenLeaf Retail",
    source: "Advertisement",
    salesAgent: "69afa86e299b681b8579dfe9",
    status: "Proposal Sent",
    tags: ["Negotiation", "Decision Pending"],
    timeToClose: 18,
    priority: "High",
  },
  {
    name: "Orion Digital",
    source: "Email",
    salesAgent: "69af8801fc00d3ee60bcd059",
    status: "Closed",
    tags: ["Deal Won", "Premium Client"],
    timeToClose: 12,
    priority: "High",
    closedAt: "2026-02-01T10:00:00.000Z",
  },
  {
    name: "Zenith Logistics",
    source: "Referral",
    salesAgent: "69af8b181716f5cd17e8e781",
    status: "New",
    tags: ["Logistics", "High Potential"],
    timeToClose: 35,
    priority: "Medium",
  },
  {
    name: "Alpha Systems",
    source: "Website",
    salesAgent: "69af8b361716f5cd17e8e784",
    status: "Contacted",
    tags: ["Product Demo", "Tech Discussion"],
    timeToClose: 28,
    priority: "Medium",
  },
  {
    name: "BlueWave Marketing",
    source: "Email",
    salesAgent: "69afa86e299b681b8579dfe9",
    status: "Qualified",
    tags: ["Marketing", "B2B Opportunity"],
    timeToClose: 20,
    priority: "Low",
  },
  {
    name: "Delta Innovations",
    source: "Cold Call",
    salesAgent: "69af8801fc00d3ee60bcd059",
    status: "Proposal Sent",
    tags: ["Large Contract", "Legal Review"],
    timeToClose: 24,
    priority: "High",
  },
  {
    name: "Skyline Builders",
    source: "Advertisement",
    salesAgent: "69af8b181716f5cd17e8e781",
    status: "Closed",
    tags: ["Construction", "Repeat Client"],
    timeToClose: 14,
    priority: "Medium",
    closedAt: "2026-02-03T11:30:00.000Z",
  },

  {
    name: "Quantum Analytics",
    source: "Website",
    salesAgent: "69af8b361716f5cd17e8e784",
    status: "New",
    tags: ["Analytics", "Startup"],
    timeToClose: 40,
    priority: "Low",
  },
  {
    name: "Vertex Industries",
    source: "Referral",
    salesAgent: "69afa86e299b681b8579dfe9",
    status: "Contacted",
    tags: ["Manufacturing", "Follow Up"],
    timeToClose: 26,
    priority: "Medium",
  },
  {
    name: "Apex Finance",
    source: "Email",
    salesAgent: "69af8801fc00d3ee60bcd059",
    status: "Qualified",
    tags: ["Finance", "Budget Approved"],
    timeToClose: 21,
    priority: "High",
  },
  {
    name: "Nimbus Cloud",
    source: "Website",
    salesAgent: "69af8b181716f5cd17e8e781",
    status: "Proposal Sent",
    tags: ["Cloud Services", "Enterprise Deal"],
    timeToClose: 17,
    priority: "High",
  },
  {
    name: "Pulse Healthcare",
    source: "Other",
    salesAgent: "69af8b361716f5cd17e8e784",
    status: "Closed",
    tags: ["Healthcare", "Strategic Partnership"],
    timeToClose: 15,
    priority: "High",
    closedAt: "2026-02-05T09:45:00.000Z",
  },
  {
    name: "Everest Security",
    source: "Cold Call",
    salesAgent: "69afa86e299b681b8579dfe9",
    status: "New",
    tags: ["Security", "SMB Client"],
    timeToClose: 32,
    priority: "Medium",
  },
  {
    name: "Urban Retailers",
    source: "Advertisement",
    salesAgent: "69af8801fc00d3ee60bcd059",
    status: "Contacted",
    tags: ["Retail", "Product Inquiry"],
    timeToClose: 27,
    priority: "Medium",
  },
  {
    name: "Helios Energy",
    source: "Referral",
    salesAgent: "69af8b181716f5cd17e8e781",
    status: "Qualified",
    tags: ["Energy", "Long Term"],
    timeToClose: 23,
    priority: "High",
  },
  {
    name: "Pixel Studios",
    source: "Email",
    salesAgent: "69af8b361716f5cd17e8e784",
    status: "Proposal Sent",
    tags: ["Creative", "Brand Deal"],
    timeToClose: 19,
    priority: "Low",
  },
  {
    name: "Atlas Manufacturing",
    source: "Cold Call",
    salesAgent: "69afa86e299b681b8579dfe9",
    status: "Closed",
    tags: ["Manufacturing", "Deal Finalized"],
    timeToClose: 13,
    priority: "Medium",
    closedAt: "2026-02-07T10:20:00.000Z",
  },

  {
    name: "NextGen Robotics",
    source: "Website",
    salesAgent: "69af8801fc00d3ee60bcd059",
    status: "New",
    tags: ["Robotics", "Tech Startup"],
    timeToClose: 36,
    priority: "High",
  },
  {
    name: "Summit Finance",
    source: "Referral",
    salesAgent: "69af8b181716f5cd17e8e781",
    status: "Contacted",
    tags: ["Finance", "Consultation"],
    timeToClose: 29,
    priority: "Medium",
  },
  {
    name: "Metro Transport",
    source: "Advertisement",
    salesAgent: "69af8b361716f5cd17e8e784",
    status: "Qualified",
    tags: ["Transport", "Fleet Deal"],
    timeToClose: 21,
    priority: "Medium",
  },
  {
    name: "Bright Media",
    source: "Email",
    salesAgent: "69afa86e299b681b8579dfe9",
    status: "Proposal Sent",
    tags: ["Media", "Campaign Deal"],
    timeToClose: 18,
    priority: "Low",
  },
  {
    name: "Delta Finance",
    source: "Website",
    salesAgent: "69af8801fc00d3ee60bcd059",
    status: "Closed",
    tags: ["Finance", "Corporate Client"],
    timeToClose: 11,
    priority: "High",
    closedAt: "2026-02-10T09:00:00.000Z",
  },
];